// <auto-generated />
using System;
using ClothesStoreMobileApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClothesStoreMobileApplication.Migrations
{
    [DbContext(typeof(ClothesStoreContext))]
    [Migration("20241017005641_update-data")]
    partial class updatedata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Avt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AdminId");

                    b.HasIndex("UserId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Avt = "https://i.imgur.com/83aoGyM.gif",
                            Cover = "admin_cover.jpg",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            CartId = 1,
                            CustomerId = 1
                        });
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            CartItemId = 1,
                            CartId = 1,
                            ProductId = 1,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Img = "https://plus.unsplash.com/premium_photo-1673356301535-2cc45bcc79e4?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "T-Shirts"
                        },
                        new
                        {
                            CategoryId = 2,
                            Img = "https://plus.unsplash.com/premium_photo-1674828601362-afb73c907ebe?q=80&w=1953&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Jeans"
                        },
                        new
                        {
                            CategoryId = 3,
                            Img = "https://plus.unsplash.com/premium_photo-1676212689512-5b66701912d4?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Jackets"
                        },
                        new
                        {
                            CategoryId = 4,
                            Img = "https://plus.unsplash.com/premium_photo-1682435561654-20d84cef00eb?q=80&w=1918&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Shoes"
                        });
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Chat", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("UserId1")
                        .HasColumnType("int");

                    b.Property<int>("UserId2")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId2");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            UserId1 = 3,
                            UserId2 = 2
                        });
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.ChatMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Media")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            Content = "Hello, I have a question about my order.",
                            RoomId = 1,
                            SenderId = 3,
                            Timestamp = new DateTime(2024, 10, 17, 7, 56, 40, 545, DateTimeKind.Local).AddTicks(7406)
                        },
                        new
                        {
                            MessageId = 2,
                            Content = "Sure, how can I assist you?",
                            RoomId = 1,
                            SenderId = 2,
                            Timestamp = new DateTime(2024, 10, 17, 7, 56, 40, 545, DateTimeKind.Local).AddTicks(7409)
                        },
                        new
                        {
                            MessageId = 3,
                            Content = "Is there anything specific you need help with?",
                            RoomId = 1,
                            SenderId = 2,
                            Timestamp = new DateTime(2024, 10, 17, 7, 56, 40, 545, DateTimeKind.Local).AddTicks(7411)
                        });
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Avt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "456 Customer Avenue, City Y",
                            Avt = "https://images.unsplash.com/photo-1556745753-b2904692b3cd?q=80&w=1973&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "John Doe",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Discount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("DiscountId");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            DiscountId = 1,
                            Code = "SUMMER20",
                            Description = "20% off on summer collection",
                            DiscountPercentage = 20m,
                            EndDate = new DateTime(2024, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 100,
                            StartDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true
                        },
                        new
                        {
                            DiscountId = 2,
                            Code = "WINTER15",
                            Description = "15% off on winter collection",
                            DiscountPercentage = 15m,
                            EndDate = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true
                        });
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Option", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionId"));

                    b.Property<int>("OptionGroupId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("OptionId");

                    b.HasIndex("OptionGroupId");

                    b.HasIndex("ProductId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            OptionId = 1,
                            OptionGroupId = 1,
                            Price = 1.0m,
                            ProductId = 1
                        },
                        new
                        {
                            OptionId = 2,
                            OptionGroupId = 2,
                            Price = 1.5m,
                            ProductId = 1
                        },
                        new
                        {
                            OptionId = 3,
                            OptionGroupId = 3,
                            Price = 2.0m,
                            ProductId = 1
                        },
                        new
                        {
                            OptionId = 4,
                            OptionGroupId = 4,
                            Price = 2.5m,
                            ProductId = 1
                        },
                        new
                        {
                            OptionId = 5,
                            OptionGroupId = 1,
                            Price = 1.0m,
                            ProductId = 2
                        },
                        new
                        {
                            OptionId = 6,
                            OptionGroupId = 2,
                            Price = 1.8m,
                            ProductId = 2
                        },
                        new
                        {
                            OptionId = 7,
                            OptionGroupId = 3,
                            Price = 2.2m,
                            ProductId = 2
                        },
                        new
                        {
                            OptionId = 8,
                            OptionGroupId = 5,
                            Price = 2.7m,
                            ProductId = 2
                        },
                        new
                        {
                            OptionId = 9,
                            OptionGroupId = 1,
                            Price = 1.3m,
                            ProductId = 3
                        },
                        new
                        {
                            OptionId = 10,
                            OptionGroupId = 4,
                            Price = 3.0m,
                            ProductId = 3
                        },
                        new
                        {
                            OptionId = 11,
                            OptionGroupId = 6,
                            Price = 3.5m,
                            ProductId = 3
                        },
                        new
                        {
                            OptionId = 12,
                            OptionGroupId = 7,
                            Price = 4.0m,
                            ProductId = 3
                        },
                        new
                        {
                            OptionId = 13,
                            OptionGroupId = 8,
                            Price = 4.5m,
                            ProductId = 4
                        },
                        new
                        {
                            OptionId = 14,
                            OptionGroupId = 9,
                            Price = 5.0m,
                            ProductId = 4
                        },
                        new
                        {
                            OptionId = 15,
                            OptionGroupId = 10,
                            Price = 5.5m,
                            ProductId = 4
                        },
                        new
                        {
                            OptionId = 16,
                            OptionGroupId = 2,
                            Price = 1.5m,
                            ProductId = 5
                        },
                        new
                        {
                            OptionId = 17,
                            OptionGroupId = 3,
                            Price = 2.0m,
                            ProductId = 5
                        },
                        new
                        {
                            OptionId = 18,
                            OptionGroupId = 5,
                            Price = 2.5m,
                            ProductId = 5
                        },
                        new
                        {
                            OptionId = 19,
                            OptionGroupId = 6,
                            Price = 3.0m,
                            ProductId = 6
                        },
                        new
                        {
                            OptionId = 20,
                            OptionGroupId = 7,
                            Price = 3.5m,
                            ProductId = 6
                        },
                        new
                        {
                            OptionId = 21,
                            OptionGroupId = 1,
                            Price = 1.0m,
                            ProductId = 7
                        },
                        new
                        {
                            OptionId = 22,
                            OptionGroupId = 8,
                            Price = 4.0m,
                            ProductId = 7
                        },
                        new
                        {
                            OptionId = 23,
                            OptionGroupId = 9,
                            Price = 4.5m,
                            ProductId = 7
                        },
                        new
                        {
                            OptionId = 24,
                            OptionGroupId = 2,
                            Price = 1.5m,
                            ProductId = 8
                        },
                        new
                        {
                            OptionId = 25,
                            OptionGroupId = 10,
                            Price = 5.5m,
                            ProductId = 8
                        },
                        new
                        {
                            OptionId = 26,
                            OptionGroupId = 3,
                            Price = 2.0m,
                            ProductId = 8
                        },
                        new
                        {
                            OptionId = 27,
                            OptionGroupId = 1,
                            Price = 1.0m,
                            ProductId = 9
                        },
                        new
                        {
                            OptionId = 28,
                            OptionGroupId = 6,
                            Price = 3.5m,
                            ProductId = 9
                        },
                        new
                        {
                            OptionId = 29,
                            OptionGroupId = 7,
                            Price = 4.0m,
                            ProductId = 9
                        },
                        new
                        {
                            OptionId = 30,
                            OptionGroupId = 5,
                            Price = 2.5m,
                            ProductId = 10
                        },
                        new
                        {
                            OptionId = 31,
                            OptionGroupId = 8,
                            Price = 4.5m,
                            ProductId = 10
                        },
                        new
                        {
                            OptionId = 32,
                            OptionGroupId = 9,
                            Price = 5.0m,
                            ProductId = 10
                        },
                        new
                        {
                            OptionId = 33,
                            OptionGroupId = 10,
                            Price = 5.5m,
                            ProductId = 11
                        },
                        new
                        {
                            OptionId = 34,
                            OptionGroupId = 2,
                            Price = 1.7m,
                            ProductId = 11
                        },
                        new
                        {
                            OptionId = 35,
                            OptionGroupId = 3,
                            Price = 2.3m,
                            ProductId = 11
                        },
                        new
                        {
                            OptionId = 36,
                            OptionGroupId = 4,
                            Price = 2.9m,
                            ProductId = 12
                        },
                        new
                        {
                            OptionId = 37,
                            OptionGroupId = 5,
                            Price = 3.4m,
                            ProductId = 12
                        },
                        new
                        {
                            OptionId = 38,
                            OptionGroupId = 7,
                            Price = 4.4m,
                            ProductId = 13
                        },
                        new
                        {
                            OptionId = 39,
                            OptionGroupId = 8,
                            Price = 4.9m,
                            ProductId = 13
                        },
                        new
                        {
                            OptionId = 40,
                            OptionGroupId = 9,
                            Price = 5.4m,
                            ProductId = 14
                        },
                        new
                        {
                            OptionId = 41,
                            OptionGroupId = 10,
                            Price = 5.9m,
                            ProductId = 14
                        },
                        new
                        {
                            OptionId = 42,
                            OptionGroupId = 6,
                            Price = 3.8m,
                            ProductId = 15
                        },
                        new
                        {
                            OptionId = 43,
                            OptionGroupId = 2,
                            Price = 1.9m,
                            ProductId = 15
                        },
                        new
                        {
                            OptionId = 44,
                            OptionGroupId = 4,
                            Price = 2.6m,
                            ProductId = 16
                        },
                        new
                        {
                            OptionId = 45,
                            OptionGroupId = 8,
                            Price = 4.7m,
                            ProductId = 16
                        },
                        new
                        {
                            OptionId = 46,
                            OptionGroupId = 1,
                            Price = 1.2m,
                            ProductId = 17
                        },
                        new
                        {
                            OptionId = 47,
                            OptionGroupId = 3,
                            Price = 2.5m,
                            ProductId = 17
                        },
                        new
                        {
                            OptionId = 48,
                            OptionGroupId = 5,
                            Price = 3.1m,
                            ProductId = 18
                        },
                        new
                        {
                            OptionId = 49,
                            OptionGroupId = 6,
                            Price = 3.7m,
                            ProductId = 18
                        },
                        new
                        {
                            OptionId = 50,
                            OptionGroupId = 7,
                            Price = 4.2m,
                            ProductId = 19
                        },
                        new
                        {
                            OptionId = 51,
                            OptionGroupId = 8,
                            Price = 4.8m,
                            ProductId = 19
                        },
                        new
                        {
                            OptionId = 52,
                            OptionGroupId = 9,
                            Price = 5.3m,
                            ProductId = 20
                        },
                        new
                        {
                            OptionId = 53,
                            OptionGroupId = 10,
                            Price = 5.7m,
                            ProductId = 20
                        },
                        new
                        {
                            OptionId = 54,
                            OptionGroupId = 1,
                            Price = 1.1m,
                            ProductId = 21
                        },
                        new
                        {
                            OptionId = 55,
                            OptionGroupId = 2,
                            Price = 1.5m,
                            ProductId = 21
                        },
                        new
                        {
                            OptionId = 56,
                            OptionGroupId = 3,
                            Price = 2.0m,
                            ProductId = 22
                        },
                        new
                        {
                            OptionId = 57,
                            OptionGroupId = 4,
                            Price = 2.5m,
                            ProductId = 22
                        },
                        new
                        {
                            OptionId = 58,
                            OptionGroupId = 5,
                            Price = 3.0m,
                            ProductId = 23
                        },
                        new
                        {
                            OptionId = 59,
                            OptionGroupId = 6,
                            Price = 3.5m,
                            ProductId = 23
                        },
                        new
                        {
                            OptionId = 60,
                            OptionGroupId = 7,
                            Price = 4.0m,
                            ProductId = 24
                        },
                        new
                        {
                            OptionId = 61,
                            OptionGroupId = 8,
                            Price = 4.5m,
                            ProductId = 24
                        },
                        new
                        {
                            OptionId = 62,
                            OptionGroupId = 9,
                            Price = 5.0m,
                            ProductId = 25
                        },
                        new
                        {
                            OptionId = 63,
                            OptionGroupId = 10,
                            Price = 5.5m,
                            ProductId = 25
                        });
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DiscountCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShipFee")
                        .HasColumnType("int");

                    b.Property<string>("ShipMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            DiscountCode = "SUMMER20",
                            OrderDate = new DateTime(2024, 10, 17, 7, 56, 40, 545, DateTimeKind.Local).AddTicks(7199),
                            PaymentMethod = "credit_card",
                            ShipAddress = "123 Main St, Cityville",
                            ShipFee = 5,
                            ShipMail = "john@example.com",
                            ShipName = "John Doe",
                            ShipPhone = "123-456-7890",
                            Status = "pending",
                            TotalAmount = 100.0
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 1,
                            OrderDate = new DateTime(2024, 10, 17, 7, 56, 40, 545, DateTimeKind.Local).AddTicks(7205),
                            PaymentMethod = "paypal",
                            ShipAddress = "456 Elm St, Townsville",
                            ShipFee = 0,
                            ShipMail = "jane@example.com",
                            ShipName = "Jane Smith",
                            ShipPhone = "098-765-4321",
                            Status = "completed",
                            TotalAmount = 150.0
                        });
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderItemId = 1,
                            Note = "Please gift wrap",
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            OrderItemId = 2,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemId = 3,
                            Note = "Urgent delivery",
                            OrderId = 2,
                            ProductId = 1,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("NewPrice")
                        .HasColumnType("bigint");

                    b.Property<long?>("OldPrice")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("QuantitySold")
                        .HasColumnType("bigint");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CartId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Description for T-Shirt 1",
                            Img = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=1780&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "T-Shirt 1",
                            NewPrice = 15L,
                            OldPrice = 20L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Description for T-Shirt 2",
                            Img = "https://images.unsplash.com/photo-1485218126466-34e6392ec754?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "T-Shirt 2",
                            NewPrice = 18L,
                            OldPrice = 23L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Description for T-Shirt 3",
                            Img = "https://plus.unsplash.com/premium_photo-1661373644394-ebc6f569826c?q=80&w=1888&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "T-Shirt 3",
                            NewPrice = 20L,
                            OldPrice = 25L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            Description = "Description for T-Shirt 4",
                            Img = "https://images.unsplash.com/photo-1522706604291-210a56c3b376?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "T-Shirt 4",
                            NewPrice = 22L,
                            OldPrice = 27L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            Description = "Description for T-Shirt 5",
                            Img = "https://images.unsplash.com/photo-1592492135673-55966d3b541a?q=80&w=1986&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "T-Shirt 5",
                            NewPrice = 25L,
                            OldPrice = 30L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            Description = "Description for T-Shirt 6",
                            Img = "https://images.unsplash.com/photo-1617310208925-9ad2a0391d85?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "T-Shirt 6",
                            NewPrice = 28L,
                            OldPrice = 33L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            Description = "Description for T-Shirt 7",
                            Img = "https://plus.unsplash.com/premium_photo-1670088464876-e1fa625c8697?q=80&w=1886&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "T-Shirt 7",
                            NewPrice = 30L,
                            OldPrice = 35L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1,
                            Description = "Description for T-Shirt 8",
                            Img = "https://images.unsplash.com/photo-1581791538302-03537b9c97bf?q=80&w=1779&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "T-Shirt 8",
                            NewPrice = 32L,
                            OldPrice = 37L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 1
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 1,
                            Description = "Description for T-Shirt 9",
                            Img = "https://plus.unsplash.com/premium_photo-1687850859076-b8e74a1ac8fa?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "T-Shirt 9",
                            NewPrice = 35L,
                            OldPrice = 40L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 1
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 1,
                            Description = "Description for T-Shirt 10",
                            Img = "https://images.unsplash.com/photo-1521097769011-905fc0291094?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "T-Shirt 10",
                            NewPrice = 37L,
                            OldPrice = 42L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 1
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 2,
                            Description = "Description for Jeans 1",
                            Img = "https://plus.unsplash.com/premium_photo-1674828601362-afb73c907ebe?q=80&w=1953&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Jeans 1",
                            NewPrice = 30L,
                            OldPrice = 40L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 2
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 2,
                            Description = "Description for Jeans 2",
                            Img = "https://images.unsplash.com/photo-1604176354204-9268737828e4?q=80&w=1780&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Jeans 2",
                            NewPrice = 32L,
                            OldPrice = 42L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 2
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 2,
                            Description = "Description for Jeans 3",
                            Img = "https://images.unsplash.com/photo-1542272604-787c3835535d?q=80&w=1926&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Jeans 3",
                            NewPrice = 34L,
                            OldPrice = 44L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 2
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 2,
                            Description = "Description for Jeans 4",
                            Img = "https://images.unsplash.com/photo-1623120389902-6c846c80f4c8?q=80&w=1780&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Jeans 4",
                            NewPrice = 36L,
                            OldPrice = 46L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 2
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 2,
                            Description = "Description for Jeans 5",
                            Img = "https://plus.unsplash.com/premium_photo-1675877946243-bc3f83e65afe?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Jeans 5",
                            NewPrice = 38L,
                            OldPrice = 48L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 2
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 2,
                            Description = "Description for Jeans 6",
                            Img = "https://images.unsplash.com/photo-1608613517869-07b097abbcf3?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Jeans 6",
                            NewPrice = 40L,
                            OldPrice = 50L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 2
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 2,
                            Description = "Description for Jeans 7",
                            Img = "https://images.unsplash.com/photo-1474570094496-a0e20f2e8050?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Jeans 7",
                            NewPrice = 42L,
                            OldPrice = 52L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 2
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 2,
                            Description = "Description for Jeans 8",
                            Img = "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Jeans 8",
                            NewPrice = 44L,
                            OldPrice = 54L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 2
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 2,
                            Description = "Description for Jeans 9",
                            Img = "https://plus.unsplash.com/premium_photo-1674828601017-2b8d4ea90aca?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Jeans 9",
                            NewPrice = 46L,
                            OldPrice = 56L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 2
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 2,
                            Description = "Description for Jeans 10",
                            Img = "https://images.unsplash.com/photo-1589561818145-eb2a4ba71a3c?q=80&w=2069&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Jeans 10",
                            NewPrice = 48L,
                            OldPrice = 58L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 2
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 3,
                            Description = "Description for Jacket 1",
                            Img = "https://plus.unsplash.com/premium_photo-1671030274122-b6ac34f87b8b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Jacket 1",
                            NewPrice = 50L,
                            OldPrice = 60L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 2
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 3,
                            Description = "Description for Jacket 2",
                            Img = "https://images.unsplash.com/photo-1542327897-d73f4005b533?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Jacket 2",
                            NewPrice = 55L,
                            OldPrice = 65L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 2
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 3,
                            Description = "Description for Jacket 3",
                            Img = "https://images.unsplash.com/photo-1576993537667-c6d2386f90a2?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Jacket 3",
                            NewPrice = 58L,
                            OldPrice = 68L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 2
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 3,
                            Description = "Description for Jacket 4",
                            Img = "https://images.unsplash.com/photo-1551318181-655e9748c0a6?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Jacket 4",
                            NewPrice = 60L,
                            OldPrice = 70L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 2
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 3,
                            Description = "Description for Jacket 5",
                            Img = "https://plus.unsplash.com/premium_photo-1683121231638-4100d7f6deb2?q=80&w=1888&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Jacket 5",
                            NewPrice = 62L,
                            OldPrice = 72L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 2
                        },
                        new
                        {
                            ProductId = 31,
                            CategoryId = 4,
                            Description = "Description for Shoe 1",
                            Img = "https://plus.unsplash.com/premium_photo-1682435561654-20d84cef00eb?q=80&w=1918&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Shoe 1",
                            NewPrice = 40L,
                            OldPrice = 50L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 1
                        },
                        new
                        {
                            ProductId = 32,
                            CategoryId = 4,
                            Description = "Description for Shoe 2",
                            Img = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Shoe 2",
                            NewPrice = 42L,
                            OldPrice = 52L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 1
                        },
                        new
                        {
                            ProductId = 33,
                            CategoryId = 4,
                            Description = "Description for Shoe 3",
                            Img = "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Shoe 3",
                            NewPrice = 45L,
                            OldPrice = 55L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 1
                        },
                        new
                        {
                            ProductId = 34,
                            CategoryId = 4,
                            Description = "Description for Shoe 4",
                            Img = "https://images.unsplash.com/photo-1561909848-977d0617f275?q=80&w=1780&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Shoe 4",
                            NewPrice = 48L,
                            OldPrice = 58L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 1
                        },
                        new
                        {
                            ProductId = 35,
                            CategoryId = 4,
                            Description = "Description for Shoe 5",
                            Img = "https://plus.unsplash.com/premium_photo-1682125177822-63c27a3830ea?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Shoe 5",
                            NewPrice = 50L,
                            OldPrice = 60L,
                            Quantity = 100,
                            QuantitySold = 0L,
                            SellerId = 1
                        });
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.ProductOption", b =>
                {
                    b.Property<int>("ProductOptionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductOptionsId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductOptionsId");

                    b.ToTable("ProductOptions");

                    b.HasData(
                        new
                        {
                            ProductOptionsId = 1,
                            Name = "Size",
                            NameDescription = "Small"
                        },
                        new
                        {
                            ProductOptionsId = 2,
                            Name = "Size",
                            NameDescription = "Medium"
                        },
                        new
                        {
                            ProductOptionsId = 3,
                            Name = "Size",
                            NameDescription = "Large"
                        },
                        new
                        {
                            ProductOptionsId = 4,
                            Name = "Color",
                            NameDescription = "Blue"
                        },
                        new
                        {
                            ProductOptionsId = 5,
                            Name = "Color",
                            NameDescription = "Red"
                        },
                        new
                        {
                            ProductOptionsId = 6,
                            Name = "Color",
                            NameDescription = "Green"
                        },
                        new
                        {
                            ProductOptionsId = 7,
                            Name = "Material",
                            NameDescription = "Cotton"
                        },
                        new
                        {
                            ProductOptionsId = 8,
                            Name = "Material",
                            NameDescription = "Polyester"
                        },
                        new
                        {
                            ProductOptionsId = 9,
                            Name = "Material",
                            NameDescription = "Wool"
                        },
                        new
                        {
                            ProductOptionsId = 10,
                            Name = "Style",
                            NameDescription = "Casual"
                        },
                        new
                        {
                            ProductOptionsId = 11,
                            Name = "Style",
                            NameDescription = "Formal"
                        },
                        new
                        {
                            ProductOptionsId = 12,
                            Name = "Length",
                            NameDescription = "Short"
                        },
                        new
                        {
                            ProductOptionsId = 13,
                            Name = "Length",
                            NameDescription = "Long"
                        },
                        new
                        {
                            ProductOptionsId = 14,
                            Name = "Fit",
                            NameDescription = "Regular"
                        },
                        new
                        {
                            ProductOptionsId = 15,
                            Name = "Fit",
                            NameDescription = "Slim"
                        },
                        new
                        {
                            ProductOptionsId = 16,
                            Name = "Season",
                            NameDescription = "Summer"
                        },
                        new
                        {
                            ProductOptionsId = 17,
                            Name = "Season",
                            NameDescription = "Winter"
                        },
                        new
                        {
                            ProductOptionsId = 18,
                            Name = "Gender",
                            NameDescription = "Men"
                        },
                        new
                        {
                            ProductOptionsId = 19,
                            Name = "Gender",
                            NameDescription = "Women"
                        },
                        new
                        {
                            ProductOptionsId = 20,
                            Name = "Origin",
                            NameDescription = "Imported"
                        });
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.ReplyReview", b =>
                {
                    b.Property<int>("ReplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReplyId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReplyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReplyId");

                    b.HasIndex("ReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("ReplyReviews");

                    b.HasData(
                        new
                        {
                            ReplyId = 1,
                            Content = "Thank you for your feedback!",
                            ReplyDate = new DateTime(2024, 10, 17, 7, 56, 40, 545, DateTimeKind.Local).AddTicks(7328),
                            ReviewId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ReplyId = 2,
                            Content = "We appreciate your input!",
                            ReplyDate = new DateTime(2024, 10, 17, 7, 56, 40, 545, DateTimeKind.Local).AddTicks(7331),
                            ReviewId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Comment = "Excellent product!",
                            CustomerId = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 2,
                            Comment = "Very good, but could improve.",
                            CustomerId = 1,
                            OrderId = 2,
                            ProductId = 1,
                            Rating = 4
                        });
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Seller", b =>
                {
                    b.Property<int>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SellerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Avt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SellerId");

                    b.HasIndex("UserId");

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            SellerId = 1,
                            Address = "123 Fashion Street, City X",
                            Avt = "https://i.imgur.com/thZDKR1.png",
                            CompanyName = "Fashion World",
                            Cover = "https://i.imgur.com/nIBeNMD.jpeg",
                            Description = "A well-known fashion retailer offering high-quality garments.",
                            UserId = 2
                        },
                        new
                        {
                            SellerId = 2,
                            Address = "456 Shoe Street, City Y",
                            Avt = "https://i.imgur.com/7ZIv1jz.png",
                            CompanyName = "Shoe Haven",
                            Cover = "https://i.imgur.com/7ZIv1jz.png",
                            Description = "A leading shoe retailer offering a wide range of footwear.",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@example.com",
                            Password = "adminpassword",
                            Phone = "0123456789",
                            Status = true,
                            UserType = 0,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "seller1@example.com",
                            Password = "seller1password",
                            Phone = "0987654321",
                            Status = true,
                            UserType = 1,
                            Username = "seller1"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "customer1@example.com",
                            Password = "customer1password",
                            Phone = "0123987654",
                            Status = true,
                            UserType = 2,
                            Username = "customer1"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "seller2@example.com",
                            Password = "seller2password",
                            Phone = "0987123456",
                            Status = true,
                            UserType = 1,
                            Username = "seller2"
                        });
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Admin", b =>
                {
                    b.HasOne("ClothesStoreMobileApplication.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Cart", b =>
                {
                    b.HasOne("ClothesStoreMobileApplication.Models.Customer", "Customer")
                        .WithMany("Carts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.CartItem", b =>
                {
                    b.HasOne("ClothesStoreMobileApplication.Models.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothesStoreMobileApplication.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Chat", b =>
                {
                    b.HasOne("ClothesStoreMobileApplication.Models.User", "User1")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothesStoreMobileApplication.Models.User", "User2")
                        .WithMany()
                        .HasForeignKey("UserId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.ChatMessage", b =>
                {
                    b.HasOne("ClothesStoreMobileApplication.Models.Chat", "Chat")
                        .WithMany("ChatMessages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothesStoreMobileApplication.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Customer", b =>
                {
                    b.HasOne("ClothesStoreMobileApplication.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Option", b =>
                {
                    b.HasOne("ClothesStoreMobileApplication.Models.ProductOption", "ProductOptions")
                        .WithMany("Options")
                        .HasForeignKey("OptionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothesStoreMobileApplication.Models.Product", "Product")
                        .WithMany("Options")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductOptions");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Order", b =>
                {
                    b.HasOne("ClothesStoreMobileApplication.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.OrderItem", b =>
                {
                    b.HasOne("ClothesStoreMobileApplication.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothesStoreMobileApplication.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Product", b =>
                {
                    b.HasOne("ClothesStoreMobileApplication.Models.Cart", null)
                        .WithMany("Products")
                        .HasForeignKey("CartId");

                    b.HasOne("ClothesStoreMobileApplication.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("ClothesStoreMobileApplication.Models.Seller", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("SellerId");

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.ReplyReview", b =>
                {
                    b.HasOne("ClothesStoreMobileApplication.Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothesStoreMobileApplication.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Review", b =>
                {
                    b.HasOne("ClothesStoreMobileApplication.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("ClothesStoreMobileApplication.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.HasOne("ClothesStoreMobileApplication.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId");

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Seller", b =>
                {
                    b.HasOne("ClothesStoreMobileApplication.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Cart", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Chat", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Customer", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Product", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.ProductOption", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("ClothesStoreMobileApplication.Models.Seller", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
