name: Sync Fork with Upstream

on:
  repository_dispatch:
    types: [sync]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout fork repository
      uses: actions/checkout@v2

    - name: Set up Git to track upstream
      run: |
        git remote add upstream https://github.com/Raikungfu/ClothesStoreMobileAPI
        git fetch upstream
        git checkout main
        git merge upstream/main
        git push origin main